language: node_js
node_js:
- '10'
warnings_are_errors: false
install:
- npm install
script:
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  token:
    secure: Zg268vqdt3RgDx/2pHucDKJzZ0XS09gVJlxJDJ0vwSbDIhGBZ2gKv22aNOIMPyj0af4uok7/fucR1EkQvfgHNBf8loycV8rWLMp+Y7dhmdWN9rwv64JPLuawhGuXSgF/WFieweXf/ITpXoE4TvN9pqScVLi6ohdZGOrrgBbxQ3LoR4gkamV7+CTEp7v5i2QJ2b2JseTB/E3x64J34tNtNsFbYlosGLr4B1/PhrsWffKIn2nSGs9rYB8LNCLqweEVt+2yJiklgeTCB/GdK9xrZnX6F0ApoMHMXVc9wU6A6JB/QZ91Fe73gU5Bt9PFwAFxOHqgHGLnXnLbxPVh+q7WhQ1zaLA5FEP77WSNwgAspSEHZLY73FZVp2AhY0BduXMZwFDBojMJAmDLFGG6CBig5a40/f4MgdFhxaTDopgF24ABh/p8YoKnW7Hh8vpPo5ZeI7zdEBX6jOCa9B7ZJ4fdgSDfeTS4/f2nLKb6TeaN8dJIWbAMq0MaJYd3MQ7Eonzcyd7zhoVIhkqMi1+Lyod/WgsoiULV2okx1lqR7J5XXWVnvHmcTp3Dq6e1TqRxCM9j4KArJUK4xgr7WGxU5wi0UCU3hlAW0HRTuMVUCUdY/q/YpPxhvZuxslW6HD0BxePmmdjbH9MoXMOJU2PdkAeos/xNsNXT9xOC0wYsTejxYxA=

